name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Make all
      run: make all
    - name: dir the dir
      run: |
        cd ${{ github.workspace }}
        ls
        exit -9
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
         # Artifact name
         name: dementio.deb 
         path: ${{ github.workspace }}/dementio# optional, default is artifact
