name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Install dependencies
      run: make all
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
         # Artifact name
         name: dementio.deb # optional, default is artifact
